##################### Tomcat ###################
server:
  port: 8080
  tomcat:
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
      enabled: true
    accesslog:
      enabled: true
      directory: E:/tomcat
      pattern: "%h %l %u %t \"%r\" %s %b %D"
##################### Redis ###################
spring:
  data:
    redis:
      host: 192.168.3.122
      port: 6379
      database: 0
      jedis:
        pool:
          max-active: 50
          min-idle: 20
#################### MVC ######################
  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: /static/images/
#
##################### Mybatis ###################
#mybatis:
  mapper-locations: classpath:**/mapper/*.xml
  type-aliases-package: io.kenji.seckill.domain.model
##################### RocketMQ ###################
rocketmq:
  name-server: 192.168.3.122:9876
  consumer:
    topic: stock
